export const CREDIT_CARD_APPLICATION = 'CREDIT_CARD_APPLICATION';
export const CREATE_ACCOUNT_USER = 'CREATE_ACCOUNT_USER';

export const AUTO_LOAN_APPLICATION = 'AUTO_LOAN_APPLICATION';
export const IS_ALLOW_COMPONENT = 'IS_ALLOW_COMPONENT';

export const CONTACT_INFO_COMPONENT_ALLOW = 'CONTACT_INFO_COMPONENT_ALLOW';
export const EMPLOYMENT_INFO_COMPONENT_ALLOW = 'EMPLOYMENT_INFO_COMPONENT_ALLOW';
export const APPLICATION_DESICION_COMPONENT_ALLOW = 'APPLICATION_DESICION_COMPONENT_ALLOW'; 
