const values =  {
   firstName: '',
   middleName: '',
   lastName: '',
   ssn: '',
   birthMonth: '',
   birthDay: '',
   birthYear: '',
   memberNumber: '',
   referenceFirstName: '',
   referenceLastName: '',
   referenceEmail: '',
   referencePhone: '',
   referenceRelationship: '',
   citizenship: '',
   contactMethod: '',
   contactEmail: '',
   homePhone: '',
   cellPhone: '',
   workPhone: '',
   address: '',
   zip: '',
   city: '',
   state: '',
   occupancyStatus: '',
   occupancyYears: '',
   occupancyMonths: '',
   idType: '',
   idNumber: '',
   idState: '',
   expirationMonth: '',
   expirationDay: '',
   expirationYear: '',
   monthlyIncome: '',
   employmentStatus: '',
   jobTitle: '',
   employer: '',
   employmentYears: '',
   employmentMonths: '',
   monthlyExpenses: '',
   loanType: '',
   applicationNumber: 0
}


export const initialValues = {
   isAllow: false,
   showHomeNavbarAndFooter: true,
   contactInfoComponentAllow: false,
   employmentInfoComponentAllow: false,
   applicationDecisionComponentAllow: false,
   resultApplicationComponentAllow: false,
   creditCardApplication: values,
   autoLoanApplication: {},
   createAccount: {},
   accountUserData: {},
   preApprovalResult: {}
};
